# Generated by Django 4.1.2 on 2022-10-26 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='date_realeased',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 26, 16, 23, 39, 786546)),
        ),
    ]
