# Generated by Django 4.1.2 on 2022-11-04 01:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_alter_song_date_realeased'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artiste_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='musicapp.artiste'),
        ),
        migrations.AlterField(
            model_name='song',
            name='date_realeased',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 11, 4, 2, 32, 34, 357433)),
        ),
    ]
